#!/usr/bin/env bash
# this will read the file /etc/passwd and display username & userID
while IFS=':' read -r username password uid gid gecos home shell
do
	echo "The user ${username} has the user id {uid} and home directory path of ${home}"
done < "etc/passwd"
