#!/usr/bin/env bash
# this will read the directory /etc/passwd

while IFS=':' read - username password uid gid gecos home shell
do
	echo "The user ${username} is part of the ${gid} gang, lives in ${home} and rides ${shell}. ${uid}'s place us protected by the passcode ${password}, more info about the user here: ${gecos}"
done < "/etc/passwd"
